<style>
#sideBareMenuGaucheFacturation{ visibility: hidden }

#sideBareMenuGaucheFacturation{ min-width:200px; max-width: 430px;}
</style>




<script>
$(window).load(function () {

	$('#waitMenuGaucheFacturation').toggle(false);
	$('#sideBareMenuGaucheFacturation').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheFacturation" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheFacturation">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier patient </span></a> </li>

	<li id="plus_dossier_patient" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/ajouter";?>"  >
	       <span id="nouveau_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Nouveau</span></a>
	   </div>
 
	  
	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/accouchement/liste-patient";?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	       <span id="liste_dossier_patient_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste </span></a>
	   </div>
	</li>
<!-- MENU ***Admission*** -->
<li id="admission"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Admission Patiente </span></a> 
</li>

<li id="plus_admission" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/admission";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Admission</span></a>
</div>

 <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/accouchement/liste-patients-admis";?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' />
	       <span id="liste_dossier_patient_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des Admis</span></a>
	   </div>


</li>


<!-- MENU ***Prenatales*** -->
<li id="prenatale"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Pr&eacute;natales </span></a> 
</li>

<li id="plus_prenatale" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/maternite/consultation-medecin";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>

</li>

<!-- MENU ***Accouchement*** -->
<li id="accouchement"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Accouchement </span></a> 
</li>

<li id="plus_accouchement" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/accoucher";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/liste-des-accouchements";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>
</li>



<!-- MENU ***Postnatale*** -->
<li id="postnatale"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Postnatale </span></a> 
</li>

<li id="plus_postnatale" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/postnatale/postnatale";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/postnatale/liste-des-postnatales";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>

</li>



<!-- MENU ***gynecologie*** -->
<li id="gynecologie"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Gynecologie </span></a> 
</li>

<li id="plus_gynecologie" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/gynecologie/gynecologie";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/gynecologie/liste-des-gynecologies";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>

</li>



<!-- MENU ***Planification*** -->
<li id="planification"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Planification </span></a> 
</li>

<li id="plus_planification" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/planification/planification";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/planification/liste-des-planifications";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>
</li>
	

<!-- MENU ***Hospitalisation*** -->


<li id="menu_statistiques"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' /> Statistiques</span></a> 
	</li>
	
	<li id="plus_menu_statistiques" style="background: #4a5765;" >

	   <div id="menuDesStatistiques" style="margin-left:30px; height:40px; padding-top:20px;"> <a href="<?php echo $this->basePath()."/accouchement/statistique";?>" > 
	       <img style="margin-left:5px; margin-top: -7px; width: 16px; height: 16px;" src='<?php echo $this->basePath().'/images_icons/statistics_16.png'?>' />
	       <span id="menu_statistiques_style" style="font-size:15px; color: white; font-family:Times New Roman;">Informations</span></a>
	   </div>
	   
	</li>
	

	
	
</ul>



<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU C'EST LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

if($role == 'infirmier'){ ?>
<script>
$("#hospi").toggle(false);

</script>
<?php
}
else if($role == 'medecin'|| $role=='gynecologue'){ ?>
<script>
$("#hospit").toggle(false);

</script>





<?php
}
if(( $role=='infirmier')||($role=='gynecologue')){ ?>
<!-- <script> 
 $("#deces").toggle(false);
 $("#naissance").toggle(false);
 $("#archivage").toggle(false);-->
<!-- </script> -->



<?php
     }
?>
<script>
<?php
	
	if( $role=='secretaire'){ ?>
	 <script> 
	 $("#dossier_patient").toggle(false);
	 $("#admission").toggle(false);
	</script>
}
<?php 
}
else if($role == 'sage_femme'){ ?>
<script>
$("#hospit").toggle(false);

</script>
<?php 
}
else if($role == 'stagiaire'){ ?>
<script>
$("#hospit").toggle(false);

</script>


	<?php
	     }
	?>
	<script>



function dep_admission1(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Admission Patiente </span></a></li>");
		dep_admission2();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Admission Patiente </span></a></li>");
		dep_admission1();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission').toggle(false);
$('#admission').click(function(){
	$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Admission Patiente</span></a></li>");
	dep_admission1();
$('#plus_admission').animate({
    height : 'toggle'
},1000);
return false;
});




function dep_prenatale1(){
	$('#prenatale').click(function(){
		$("#prenatale").replaceWith("<li id='prenatale'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Pr&eacute;natale </span></a></li>");
		dep_prenatale2();
	    $('#plus_prenatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_prenatale2(){
	$('#prenatale').click(function(){
		$("#prenatale").replaceWith("<li id='prenatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' />Pr&eacutenatale </span></a></li>");
		dep_prenatale1();
	    $('#plus_prenatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_prenatale').toggle(false);
$('#prenatale').click(function(){
	$("#prenatale").replaceWith("<li id='prenatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Pr&eacute;natale</span></a></li>");
	dep_prenatale1();
$('#plus_prenatale').animate({
    height : 'toggle'
},1000);
return false;
});




function dep_accouchement1(){
	$('#accouchement').click(function(){
		$("#accouchement").replaceWith("<li id='accouchement'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Accouchement </span></a></li>");
		dep_accouchement2();
	    $('#plus_accouchement').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_accouchement2(){
	$('#accouchement').click(function(){
		$("#accouchement").replaceWith("<li id='accouchement' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Accouchement </span></a></li>");
		dep_accouchement1();
	    $('#plus_accouchement').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_accouchement').toggle(false);
$('#accouchement').click(function(){
	$("#accouchement").replaceWith("<li id='accouchement' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Accouchement</span></a></li>");
	dep_accouchement1();
$('#plus_accouchement').animate({
    height : 'toggle'
},1000);
return false;
});



//TRANSFERT

function dep_transfert1(){
	$('#transfert').click(function(){
		$("#transfert").replaceWith("<li id='transfert'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> transfert </span></a></li>");
		dep_transfert2();
	    $('#plus_transfert').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_transfert2(){
	$('#transfert').click(function(){
		$("#transfert").replaceWith("<li id='transfert' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> transfert </span></a></li>");
		dep_transfert1();
	    $('#plus_transfert').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_transfert').toggle(false);
$('#transfert').click(function(){
	$("#transfert").replaceWith("<li id='transfert' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> transfert</span></a></li>");
	dep_transfert1();
$('#plus_transfert').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//postnatale


function dep_postnatale1(){
	$('#postnatale').click(function(){
		$("#postnatale").replaceWith("<li id='postnatale'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> postnatale </span></a></li>");
		dep_postnatale2();
	    $('#plus_postnatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_postnatale2(){
	$('#postnatale').click(function(){
		$("#postnatale").replaceWith("<li id='postnatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Postnatale </span></a></li>");
		dep_postnatale1();
	    $('#plus_postnatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_postnatale').toggle(false);
$('#postnatale').click(function(){
	$("#postnatale").replaceWith("<li id='postnatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Postnatale</span></a></li>");
	dep_postnatale1();
$('#plus_postnatale').animate({
    height : 'toggle'
},1000);
return false;
});

//gynecologie


function dep_gynecologie1(){
	$('#gynecologie').click(function(){
		$("#gynecologie").replaceWith("<li id='postnatale'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> gynecologie </span></a></li>");
		dep_postnatale2();
	    $('#plus_gynecologie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_gynecologie2(){
	$('#gynecologie').click(function(){
		$("#gynecologie").replaceWith("<li id='gynecologie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> gynecologie </span></a></li>");
		dep_postnatale1();
	    $('#plus_gynecologie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_gynecologie').toggle(false);
$('#gynecologie').click(function(){
	$("#gynecologie").replaceWith("<li id='gynecologie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> gynecologie</span></a></li>");
	dep_gynecologie1();
$('#plus_gynecologie').animate({
    height : 'toggle'
},1000);
return false;
});


// planification familiale


function dep_planification1(){
	$('#planification').click(function(){
		$("#planification").replaceWith("<li id='planification'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> planification </span></a></li>");
		dep_planification2();
	    $('#plus_planification').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_planification2(){
	$('#planification').click(function(){
		$("#planification").replaceWith("<li id='planification' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> planification </span></a></li>");
		dep_planification1();
	    $('#plus_planification').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_planification').toggle(false);
$('#planification').click(function(){
	$("#planification").replaceWith("<li id='planification' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> planification</span></a></li>");
	dep_planification1();
$('#plus_planification').animate({
    height : 'toggle'
},1000);
return false;
});



function dep_hospi1(){
	$('#hospi').click(function(){
		$("#hospi").replaceWith("<li id='hospi'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_hospi2();
	    $('#plus_hospi').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_hospi2(){
	$('#hospi').click(function(){
		$("#hospi").replaceWith("<li id='hospi' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_hospi1();
	    $('#plus_hospi').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_hospi').toggle(false);
$('#hospi').click(function(){
	$("#hospi").replaceWith("<li id='hospi' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Hospitalisation</span></a></li>");
	dep_hospi1();
$('#plus_hospi').animate({
    height : 'toggle'
},1000);
return false;
});





function dep_hospit1(){
	$('#hospit').click(function(){
		$("#hospi").replaceWith("<li id='hospit'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_hospit2();
	    $('#plus_hospit').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_hospit2(){
	$('#hospit').click(function(){
		$("#hospi").replaceWith("<li id='hospit' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_hospit1();
	    $('#plus_hospit').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_hospit').toggle(false);
$('#hospit').click(function(){
	$("#hospit").replaceWith("<li id='hospit' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Hospitalisation</span></a></li>");
	dep_hospit1();
$('#plus_hospit').animate({
    height : 'toggle'
},1000);
return false;
});

//*******************************************************************************
//Statistiques
function dep_menu_statistiques1(){
$('#menu_statistiques').click(function(){
	$("#menu_statistiques").replaceWith("<li id='menu_statistiques'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Statistiques </span></a></li>");
	dep_menu_statistiques2();
$('#plus_menu_statistiques').animate({
    height : 'toggle'
},1000);
return false;
});
}

function dep_menu_statistiques2(){
$('#menu_statistiques').click(function(){
	$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
	dep_menu_statistiques1();
$('#plus_menu_statistiques').animate({
    height : 'toggle'
},1000);
return false;
});
}

$('#plus_menu_statistiques').toggle(false);
$('#menu_statistiques').click(function(){
$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
dep_menu_statistiques1();
$('#plus_menu_statistiques').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier Patiente </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Dossier Patiente </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Dossier Patiente </span></a></li>");
	dep_dossier_patient1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});
//*******************************************************************************
//consultation pf
function dep_consultationpf1(){
$('#consultationpf').click(function(){
	$("#consultationpf").replaceWith("<li id='consultationpf'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> consultationPF </span></a></li>");
	dep_menu_statistiques2();
    $('#plus_consultationpf').animate({
        height : 'toggle'
    },1000);
 return false;
});
}

function dep_consultationpf2(){
$('#menu_consultationpf').click(function(){
	$("#consultationpf").replaceWith("<li id='consultationpf' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> consultationPF </span></a></li>");
	dep_menu_statistiques1();
    $('#plus_consultationpf').animate({
        height : 'toggle'
    },1000);
 return false;
});
}

$('#plus_consultationpf').toggle(false);
$('#consultationpf').click(function(){
$("#consultationpf").replaceWith("<li id='consultationpf' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> consultationpf </span></a></li>");
dep_consultationpf1();
$('#plusconsultationpf').animate({
height : 'toggle'
},1000);
return false;
});
















</script>

