<style>
#sideBareMenuGaucheFacturation{ visibility: hidden }

#sideBareMenuGaucheFacturation{ min-width:200px; max-width: 430px;}
</style>




<script>
$(window).load(function () {

	$('#waitMenuGaucheFacturation').toggle(false);
	$('#sideBareMenuGaucheFacturation').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheFacturation" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheFacturation">
	<!-- MENU ***DOSSIER PATIENT*** -->


<!-- MENU ***gynecologie*** -->
<li id="gynecologie"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Gynecologie </span></a> 
</li>

<li id="plus_gynecologie" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/gynecologie/gynecologie";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/gynecologie/liste-des-gynecologies";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>

</li>

<!-- MENU ***Prenatales*** -->
<li id="prenatale"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Pr&eacute;natales </span></a> 
</li>

<li id="plus_prenatale" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/maternite/consultation-medecin";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> En Cours...</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/maternite/liste-des-prenatales";?>"  >
   <span id="admission_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>

</li>

<!-- MENU ***Gestionsms*** -->
<li id="gestionsms"><a href="">
<span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Gestion sms </span></a> 
</li>

<li id="plus_gestionsms" style="background: #4a5765;" >

<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/liste-destinataires";?>"  >
   <span id="liste_destinataires_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Destinatires</span></a>
</div>
<div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/accouchement/historique-des-destinataires";?>"  >
   <span id="liste_destinataires_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.PNG'?>' alt='Liste' /> Historiques</span></a>
</div>
</li>




</ul>



<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU C'EST LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

if($role == 'infirmier'){ ?>
<script>
$("#hospi").toggle(false);

</script>
<?php
}
else if($role == 'medecin'|| $role=='gynecologue'){ ?>
<script>
$("#hospit").toggle(false);

</script>



<?php
}
if(( $role=='infirmier')||($role=='gynecologue')){ ?>
<!-- <script> 
 $("#deces").toggle(false);
 $("#naissance").toggle(false);
 $("#archivage").toggle(false);-->
<!-- </script> -->



<?php
     }
?>
<script>


//gynecologie


function dep_gynecologie1(){
	$('#gynecologie').click(function(){
		$("#gynecologie").replaceWith("<li id='gynecologie'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Gynecologie </span></a></li>");
		dep_postnatale2();
	    $('#plus_gynecologie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}


function dep_gynecologie2(){
	$('#gynecologie').click(function(){
		$("#gynecologie").replaceWith("<li id='gynecologie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Gynecologie </span></a></li>");
		dep_postnatale1();
	    $('#plus_gynecologie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}


$('#plus_gynecologie').toggle(false);
$('#gynecologie').click(function(){
	$("#gynecologie").replaceWith("<li id='gynecologie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Gynecologie</span></a></li>");
	dep_gynecologie1();
$('#plus_gynecologie').animate({
height : 'toggle'
},1000);
return false;
});


//Prenatale
function dep_prenatale1(){
	$('#prenatale').click(function(){
		$("#prenatale").replaceWith("<li id='prenatale'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Pr&eacute;natale </span></a></li>");
		dep_prenatale2();
	    $('#plus_prenatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_prenatale2(){
	$('#prenatale').click(function(){
		$("#prenatale").replaceWith("<li id='prenatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' />Pr&eacutenatale </span></a></li>");
		dep_prenatale1();
	    $('#plus_prenatale').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_prenatale').toggle(false);
$('#prenatale').click(function(){
	$("#prenatale").replaceWith("<li id='prenatale' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Pr&eacute;natale</span></a></li>");
	dep_prenatale1();
$('#plus_prenatale').animate({
    height : 'toggle'
},1000);
return false;
});

//Gestion sms

function dep_gestionsms1(){
	$('#gestionsms').click(function(){
		$("#gestionsms").replaceWith("<li id='gestionsms'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Gestion sms </span></a></li>");
		dep_gestionsms2();
	    $('#plus_gestionsms').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_gestionsms2(){
	$('#gestionsms').click(function(){
		$("#gestionsms").replaceWith("<li id='gestionsms' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Gestion sms </span></a></li>");
		dep_gestionsms();
	    $('#plus_gestionsms').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_gestionsms').toggle(false);
$('#gestionsms').click(function(){
	$("#gestionsms").replaceWith("<li id='gestionsms' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src=   '<?php echo $this->basePath().'/images_icons/moin-green2.png'?>' alt='Liste' /> Gestion sms</span></a></li>");
	dep_gestionsms1();
$('#plus_gestionsms').animate({
    height : 'toggle'
},1000);
return false;
});










//*******************************************************************************************************************************
//ACCOUCHEMENT


















</script>

