<?php use Maternite\View\Helpers\DateHelper; ?>


<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->
<!-- SCRIPT DU NOUVEAU CODE POUR LA GESTION DES IMAGES  -->

<!-- les scripts des images dans examen morphologique   -->
<?php
echo $this->headScript()->appendFile($this->basePath().'/js/mesjs/planification/complementcons_accordeon_controle.js');

echo $this->headLink()->appendStylesheet($this->basePath().'/css/mescss/bloquerDate.css');
 //DatePicker
echo $this->headScript()->appendFile($this->basePath().'/js/mesjs/bloquerDate.js'); //Pour bloquer certaines dates?>
<?php echo $this->headScript()->appendFile($this->basePath() . '/js/jquery/chung-timepicker.js'); 
echo $this->headScript()->appendFile($this->basePath() . '/js/jquery/jquery.timepicker.js');
echo $this->headLink()->appendStylesheet($this->basePath().'/js/jquery/jquery.timepicker.css');
echo $this->headLink()->appendStylesheet($this->basePath().'/css/chung-timepicker.css');?>
<?php echo $this->headScript()->appendFile($this->basePath() . '/js/maternite/planification/ajouterMedicaments.js'); ?>
<?php
//RECUPERATION DE LA LISTE DES MEDICAMENTS
$hopital = $this->liste_med;
?>

<?php echo $this->headScript()->appendFile($this->basePath().'/js/maternite/planification/jsAdmissionTest.js');
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/maternite/planification/jsMaternite.js' );

?>
<script>
$(function(){
  //document.getElementById('service_accueil').value="";
 // document.getElementById('heure_rv').value="";
});


//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_planification').toggle(true);
$("#planification").replaceWith("<li id='planification' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.png';?>' alt='Liste' /> planification </span></a></li>");
dep_planification1();
$('#declarer_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<!--************************************************************************************************************-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--************************************************************************************************************-->
<?php
$Control = new DateHelper ();
$today = new \DateTime ();
$AnneeActuelle = $today->format ( 'Y' );

/**
 * ***Mois 1 ****
 */
$leMois1 = $today->format ( 'm' ); // C'est le mois actuel ï¿½ l'heure du calendrier
$Dimanche1 = $Control->lePremierDimancheDuMois ();
/**
 * ***Mois 2 *****(Sauf pour le douxieme mois)
 */
$leMois2 = $leMois1 + 1;
if ($leMois2 == 13) {
	$leMois2 = 1;
	$AnneeActuelle = $AnneeActuelle + 1;
}
$Dimanche2 = $Control->lePremierDimancheDuMoisByDate ( $leMois2, $AnneeActuelle );
/**
 * ***Mois 3 ****
 */
$leMois3 = $leMois2 + 1;
if ($leMois3 == 13) {
	$leMois3 = 1;
	$AnneeActuelle = $AnneeActuelle + 1;
}
$Dimanche3 = $Control->lePremierDimancheDuMoisByDate ( $leMois3, $AnneeActuelle );
/**
 * ***Mois 4 ****
 */
$leMois4 = $leMois3 + 1;
if ($leMois4 == 13) {
	$leMois4 = 1;
	$AnneeActuelle = $AnneeActuelle + 1;
}
$Dimanche4 = $Control->lePremierDimancheDuMoisByDate ( $leMois4, $AnneeActuelle );

?>

<script>
//Bloquer les 90 jours non consultable a patir du jour, du mois actuel
/*****Mois 1*****/
mois1 = '<?php echo $leMois1?>';
dimanche1 = <?php echo $Dimanche1?>;
/*****Mois 2 *****/
if(<?php echo $leMois2?> > 9){mois2 = <?php echo $leMois2?>;}else{mois2 = '0'+'<?php echo $leMois2?>';}
dimanche2 = <?php echo $Dimanche2?>;
/*****Mois 3 *****/
if(<?php echo $leMois3?> > 9){mois3 = <?php echo $leMois3?>;}else{mois3 = '0'+'<?php echo $leMois3?>';}
dimanche3 = <?php echo $Dimanche3?>;
/*****Mois 4 *****/
if(<?php echo $leMois4?> > 9){mois4 = <?php echo $leMois4?>;}else{mois4 = '0'+'<?php echo $leMois4?>';}
dimanche4 = <?php echo $Dimanche4?>;

/***ANNEE EN COURS***/
annee = '<?php echo $AnneeActuelle?>';

/****************************
*===========================
 **************************/
        bloquerDate();
/**************************
 * ========================
 **************************/

/*<!--************************************************************************************************************-->
  <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
  <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
  <!--************************************************************************************************************--*/

</script>



<script>
function getservices(cle)
{
     $.ajax({
        type: 'POST',
        url: '<?php echo $this->basePath().'/maternite/services' ?>',
        data: 'id='+cle,
        success: function(data) {
            var result = jQuery.parseJSON(data);
            $("#service_accueil").html(result);
      },
      error:function(e){console.log(e);alert("Une erreur interne est survenue!");},
        dataType: "html"
    });

    return false;
 }

//CODE POUR LA PARTIE DES ANTECEDENTS
$(function() {
	

	$( "#tabsAntecedents" ).tabs();
	$( "#tabs" ).tabs();
	$( "#tabsInstrumental" ).tabs();

});
$(function() {
	
	$( "#tabs" ).tabs();
	$( "#tabsInstrumental" ).tabs();

});

$(function() {

	$( "#tabs" ).tabs();
	$( "#tabsInstrumental" ).tabs();

});
//pagination2();
//pagination();
AntecedentScript();

</script>




<style type='text/css'>

/*** Bouton input submit***/
/*** Bouton input submit***/
/*** Bouton input submit***/
.transf,.rendezvous,.ordonnance {
	width: 32px;
	height: 32px;
	background: url(<?php echo $this->basePath()."/images_icons/pdf.PNG"?>)
		no-repeat right top;
}

.annulertransfert,.annulerrendezvous,.annulerhospitalisation {
	position: relative;
	width: 32px;
	height: 32px;
	background: url(<?php echo $this->basePath()."/images_icons/annuler.PNG"?>)
		no-repeat right top;
	display: inline;
	float: right;
	border: transparent;
	margin-bottom: 5px;
}

.transf,.rendezvous {
	display: inline;
	float: right;
	border: transparent;
	margin-bottom: 5px;
	title: 'Imprimer';
}

.ordonnance {
	display: inline;
	border: transparent;
	margin-bottom: 5px;
	title: 'Imprimer';
	
	
	
	
	
	
	ition: relative;
	float: right;
}

.transf input,.rendezvous input,.ordonnance input,.annulertransfert input,.annulerrendezvous input,.annulerhospitalisation input
	{
	right: 0;
	top: 0;
	font-size: 100px;
	opacity: 0;
	-moz-opacity: 0;
	filter: alpha(opacity =     0);
	cursor: pointer;
	text-align: right;
	width: 32px;
	height: 32px;
}
</style>

<!-- *****************FINNNNNN images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *************** -->
<!-- *****************FINNNNNN images dans EXAMEN MORPHOLOGIQUE (plugins fancybox) *************** -->

<style>
#medicament input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#posologie input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#quantite input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#duree input[type="text"] { /*le input ou le textarea*/
	background-color: #fffffa; /*la couleur du champ*/
	height: 25px; /*la hauteur du champ input*/
	width: 190px; /* la largeur du champ input*/
}

#etat_civil {
	color: green;
	width: 70%;
}

#etat_civil td {
	vertical-align: top;
}


#etat_civil td p {
	margin-right: 15px;
	max-height: 46px;
	max-width: 95%;
	overflow: auto;
}

#etat_civil tr {
	width: 70%;
}
.autreAntF textarea{
	  width: 150%;
   height:120px;
}
#contenu {
	visibility: hidden;
}
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="wait"
	style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;">
	<span> Chargement ... </span>
</div>

<div id="contenu">
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/maternite/monstyle.css');?>



<?php
$form = $this->form;
$form->setName ( 'AVIS' );
$form->setAttribute ( 'action', $this->url ( 'planification', array (
		'action' => 'update-complement-planification' 
) ) );
//$form->setAttribute ( 'target', '_blank' );
$form->setAttribute ( 'method', 'post' );
$form->prepare ();
echo $this->form ()->openTag ( $form );
?>


<div id="accordions">
		<!-- couleur bleu du logo//#49afcd-->

		<!--*************** Accordeon ETAT CIVIL ******************-->
		<!--*************** Accordeon ETAT CIVIL ******************-->
		<!--*************** Accordeon ETAT CIVIL ******************-->
		<!--*1*-->
	
			<div style='width: 160px; font-family: police2; font-size: 17px; font-weight: bold;'>Etat
			Civil</div>
		
		
		<div id="divEtatcivil" style='max-height: 350px;'>

			<img id="faces"
				src='<?php echo $this->basePath().'/img/photos_patients/'.$this->image;?>'
				alt="Jonathan Verrecchia"
				style='float: left; margin-right: 40px; width: 105px; height: 105px;' />

			<div
				style='left: 50px; top: 160px; font-family: time new romans; position: absolute;'>
				Age: <span
					style='font-size: 19px; font-family: time new romans; color: green; font-weight: bold;'> <?php echo $this->lesdetails['AGE']; ?> ans </span>
			</div>

			<p style='color: white; opacity: 0.09;'>
				<img id="faces"
					src='<?php echo $this->basePath().'/img/photos_patients/'.$this->image;?>'
					alt="Jonathan Verrecchia"
					style='float: right; margin-right: 15px; width: 95px; height: 95px;' />
			</p>
			<table id="etat_civil">
				<tr>
					<td style='width: 27%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Pr&eacute;nom</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['PRENOM'];?></p>
						</div>
					</td>

					<td style='width: 35%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Lieu de naissance</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['LIEU_NAISSANCE'];?></p>
						</div>
					</td>

					<td style='width: 38%; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">T&eacute;l&eacute;phone</a><br>
							<p style='font-weight: bold; font-size: 17px;'><?php echo $this->lesdetails['TELEPHONE'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nom</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NOM'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nationalit&eacute; origine</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NATIONALITE_ORIGINE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Email</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['EMAIL'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Sexe</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['SEXE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Nationalit&eacute;
								actuelle</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['NATIONALITE_ACTUELLE'];?></p>
						</div>
					</td>

					<td style='font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Profession</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['PROFESSION'];?></p>
						</div>
					</td>

				</tr>

				<tr>
					<td
						style='width: 27%; font-family: police1; font-size: 12px; vertical-align: top;'>

						<div id="aa">
							<a style="text-decoration: underline;">Date de naissance</a><br>
							<p style='font-weight: bold; font-size: 19px;'>
			   		    <?php
												$date_naissance = $this->lesdetails ['DATE_NAISSANCE'];
												if ($date_naissance) {
													echo $Control->convertDate ( $this->lesdetails ['DATE_NAISSANCE'] );
												} else {
													echo "";
												}
												?> 
			   		  </p>
						</div>

					</td>

					<td
						style='display: "block"; font-family: police1; font-size: 12px;'>
						<div id="aa">
							<a style="text-decoration: underline;">Adresse</a><br>
							<p style='font-weight: bold; font-size: 19px;'><?php echo $this->lesdetails['ADRESSE'];?></p>
						</div>

					</td>

					<td
						style='display: "block"; font-family: police1; font-size: 12px; text-align: right;'>
			   	
			   	    <?php if($this->resultRV){?>
			   	       <span id='image-neon'
						style='color: red; font-weight: bold; font-size: 17px;'>Rendez-vous &agrave; <?php echo $this->resultRV; ?> </span>
			   	       
			   	    <?php } ?>
			   	</td>
				</tr>
			</table>

			<script>
          function FaireClignoterImage (){
                  $('#image-neon').fadeOut(900).delay(300).fadeIn(800);
          }
          setInterval('FaireClignoterImage()',2200);
		 </script>

			<div id="barre"></div>
			<div
				style='color: white; opacity: 1; width: 95px; height: 40px; float: right'>
				<img src='<?php echo $this->basePath().'/images_icons/fleur1.jpg'?>'
					alt="fleur1" />
			</div>

			<table id="numero" style="padding-top: 5px; width: 550px;">
				<tr style="width: 550px;">
					<td style="padding-top: 5px; width: 70px; font-size: 12px;">
						Planification:</td>
					<td style="font-weight: bold;"> <?php echo $this->id_cons;?></td>
					
						
					
				</tr>
			</table>

		</div>

		
		
		<div style='font-family: police2;font-size: 17px; font-weight: bold;'>Type d'admission</div>
		
		<div  style='max-height: 70px; '>
		 
		<table id="" style=" width: 100%;">
		
		
			<tr style="width: 100%; ">
		<td class="antecedent_go" style="width:38%;">
		<div style="float: left;">
									<label style="width: 85%; height: 30px;font-family: time new romans; text-align: left;">Type d'admission</label>
								</div>
								<div style="float: left;">
									<label style="width: 50%; height: 30px;font-family: time new romans; text-align: left;"><?php echo $this->formRow($form->get('motif_ad'));?></label>
								</div>
								
								</td>
									<td class="antecedent_go" style="width:30%;">
								<div style="float: left" id="rh">
									<label class="MotifAdmission" style="width: 285px;margin-right:15%; height: 30px;font-family: time new romans; text-align: left;">Motif <?php echo $this->formRow($form->get('motif'));?> </label>
								</div>
						</td>
						<td class="antecedent_go" style="width:30%;">
							  <div style="float: right;">
				             <label id="ser"  class="MotifAdmission" style="width: 290px; height: 30px; text-align: left; font-family: time new romans; font-size: 16px;">Service d'origine
                             <?php echo $this->formRow($form->get('service_origine'));?>
                               </label>
			                 </div>
							</td>
								
							
								
		</tr>
		
		</table>
		
		</div>	
		
		<!-- ********************Antï¿½cï¿½dents ou Terrain particulier ******************-->
<div id="" style='font-family: police2;font-size: 17px; font-weight: bold;'>Ant&eacute;c&eacute;dents</div>
 <div style="max-height: 600px;">


        <div class="accordionssssssssss">
        
        
        
        		<div style='font-family: police2;font-size: 17px; font-weight: bold;'>Gyn&eacute;co Obstc&eacute;triques</div>
		
		<div id="divEtatcivil" style='max-height: 400px;'>
		 
		<table id="" style="width: 100%;"> 
		  <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Enf_Viv </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('enf_viv'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_enf'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">G&eacute;ste </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('geste'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_geste'));?> </label>
			   </div>
								
		    </td>
		  </tr>
   	      <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Parit&eacute; </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('parite'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('note_parite'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Mort n&eacute; </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('mort_ne'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('note_mort_ne'));?> </label>
			   </div>
								
		    </td>
	 	  </tr>       
		  
	 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">C&eacute;sar </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('cesar'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_cesar'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">dystocie </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('dystocie'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_dystocie'));?> </label>
			   </div>
								
		    </td>
	 	  </tr>
		
 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Eclampsie </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('eclampsie'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_eclampsie'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Autres </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('autre_go'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_autre_go'));?> </label>
			   </div>
								
		    </td>
	 	  </tr>
		
	 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"title="Groupe Sanguin">GS</label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('groupe_sanguins'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;"title="rhésus">Rhus&nbsp;&nbsp; <?php echo $this->formRow($form->get('rhesus'));?> </label>
			   </div>
			   					
		    </td>
		    
		      <td class="antecedent_go" style="width: 50%;">
		          <div style="float: right; width: 60%; " id="">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_gs'));?> </label>
			   </div> 
			
			   </td>
		   
	 	  </tr>
		
	 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"title="Test d'emmel">TE</label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('test_emmel'));?></label>
		       </div>
	 <div style="float: right; width: 60%; " id="rh">
				   <label class="Test" style="width: 90%; height: 30px; text-align: left;">Profil &nbsp;&nbsp;<?php echo $this->formRow($form->get('profil_emmel'));?> </label>
			   </div>
			    					
		    </td>
		      <td class="antecedent_go" style="width: 50%; ">
			<div style="float: right; width: 60%; " id="">
				   <label class="Test" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp;<?php echo $this->formRow($form->get('note_emmel'));?> </label>
			   </div>
			   </td>
		   
	 	  </tr>
		

	 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Cycle</label>
		       </div>
		       <div style="float: left; width: 21%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('regularite'));?></label>
		       </div>
		      
		       <div style="float: right; width: 60%; " id="s">
				   <label class="Cycle" style="width: 90%; height: 30px; text-align: left;"title="Duree du Cycle">Dur&eacute;e&nbsp;&nbsp; <?php echo $this->formRow($form->get('duree_cycle'));?> </label>
			   </div>
		
			   </td>
	
		    
		       <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 10%; ">
			       <label class="Cycle" style="width: 90%; height: 30px; text-align: left;"title="l'abondance des regles">Qte </label>
		       </div>
		       <div style="float: left; width: 24%; ">
			       <label class="Cycle" style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('quantite_regle'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="">
				   <label class="Quantite" style="width: 95%; height: 30px; text-align: right;"title="Nombre de garniture par jours">Gtr/jr&nbsp;&nbsp; <?php echo $this->formRow($form->get('nb_garniture_jr'));?> </label>
			   </div>
								
		    </td>
		    
		    
		    
		    	   
	 	  </tr>			

			 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label  style="width: 90%; height: 30px; text-align: left;"title="Contraception Ant&eacute;ririeur">CA</label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('contraception'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="Contraception" style="width: 90%; height: 30px; text-align: left;"title="Type de Contraception ">Type&nbsp;&nbsp; <?php echo $this->formRow($form->get('type_contraception'));?> </label>
			   </div>
			    					
		    </td>
		      <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 10%; ">
			       <label class="Contraception" style="width: 90%; height: 30px; text-align: left;"title="Dur&eacute;e de Contraception ">Dur&eacute;e</label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label class="Contraception" style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('duree_contraception'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="">
				   <label class="Contraception" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_contraception'));?> </label>
			   </div>
								
		    </td>
	
		   
	 	  </tr>
	
		
	</table>
	
	
		</div>
        
        
        
		<div style='font-family: police2;font-size: 17px; font-weight: bold;'> Autres</div>
		<div id="tabsAntecedents" style='max-height: 400px;'>
			
				<ul>
					<li><a href="#tabss-1">Ant&eacute;c&eacute;dents personnels</a></li>
					<li><a href="#tabss-2">Ant&eacute;c&eacute;dents familiaux</a></li>
				</ul>

				<div id="tabss-1">

			
					

					<!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
					<!--****** ================== ANTECEDENTS PERSONNELS ================== ****** -->
					<table id="MenuAntecedentPersonnel" style="width: 100%;">

						<tr style="width: 100%;">
							
							<td style="width: 25%;">
								<div>
									<img class="image1_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image1_AP.png'?>'
										style='' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image2_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image2_AP.png'?>'
										style='' />
								</div>
							</td>
							<td style="width: 25%;">
								<div>
									<img class="image3_AP" style='cursor: pointer; width: 100%;'
										src='<?php echo $this->basepath().'/images_icons/image3_AP.png'?>'
										style='' />
								</div>
							</td>

						</tr>
					</table>
					<script> 
             $(".image4_AP").toggle(false);
             if("<?php echo $this->lesdetails['SEXE'];?>" != "Masculin" ){ $(".image4_AP").toggle(true); }
           </script>

					<table id="HabitudesDeVie" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									LES HABITUDES DE VIE
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Alcoolique <?php echo $this->formRow($form->get('AlcooliqueHV'));?></label>
								</div>
								<div style="float: left" id="dateDebAlcoolique">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutAlcooliqueHV'));?> </label>
								</div>
								<div style="float: left" id="dateFinAlcoolique">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinAlcooliqueHV'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
						
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Fumeur <?php echo $this->formRow($form->get('FumeurHV'));?></label>
								</div>
								<div style="float: left" id="dateDebFumeur">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutFumeurHV'));?></label>
								</div>
								<div style="float: left" id="dateFinFumeur">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinFumeurHV'));?></label>
								</div>
								<div style="float: left" id="nbPaquetJour">
									<label style="width: 190px; height: 30px; text-align: right;">Nbre de paquets/jour <?php echo $this->formRow($form->get('nbPaquetFumeurHV'));?></label>
								</div>
								<div style="float: left" id="nbPaquetAnnee">
									<label style="width: 110px; height: 30px; text-align: right;">
										--- nbPaquet/an --- </label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Drogu&eacute;  <?php echo $this->formRow($form->get('DroguerHV'));?></label>
								</div>
								<div style="float: left" id="dateDebDroguer">
									<label style="width: 220px; height: 30px; text-align: right;">Date d&eacute;but <?php echo $this->formRow($form->get('DateDebutDroguerHV'));?></label>
								</div>
								<div style="float: left" id="dateFinDroguer">
									<label style="width: 220px; height: 30px; text-align: right;">Date d'arr&ecirc;t <?php echo $this->formRow($form->get('DateFinDroguerHV'));?></label>
								</div>
							</td>
						</tr>
						<tr style="width: 100%;">
							<td id="BUcheckbox" style="">
								<div style="float: left;">
									<label style="width: 100px; height: 30px; text-align: right;">Autres  <?php echo $this->formRow($form->get('AutresHV'));?></label>
								</div>
								<div style="float: left" id="DivNoteAutresHV">
									<label style="width: 350px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteAutresHV'));?></label>
								</div>
							</td>
						</tr>


						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px; padding-top: 15px;'><div
									style="float: left;" id="TerminerHabitudeDeVie">Terminer</div></td>
						
						
						<tr>
					
					</table>

					<table id="AntecedentMedicaux" style="width: 100%;">
						<tr style="width: 100%;">
							<td colspan="3" style="width: 60%;">
								<div
									style="font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									LES ANT&Eacute;C&Eacute;DENTS M&Eacute;DICAUX
								</div>
							</td>
							<td></td>
							<td></td>
						</tr>
						
						
						<tr style="width: 100%; height: 50px;">
							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDiabeteAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                         
                         Diab&egrave;te 
                         <?php echo $this->formRow($form->get('DiabeteAM'));?>
                      </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderHtaAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                         
                        HTA 
                        <?php echo $this->formRow($form->get('htaAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDrepanocytoseAM"
											style='cursor: pointer; padding-right: 0px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                        
                        Dr&eacute;panocytose <?php echo $this->formRow($form->get('drepanocytoseAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderDislipidemieAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span>  
                        
                        Dislipid&eacute;mie  <?php echo $this->formRow($form->get('dislipidemieAM'));?>
                     </label>
								</div>
							</td>

							<td id="BUcheckbox" style="width: 20%;">
								<div>
									<label
										style="width: 90%; height: 30px; text-align: right; font-family: time new romans; font-size: 18px;">
										<span> <img class="imageValiderAsthmeAM"
											style='cursor: pointer; padding-right: 10px;'
											src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />
									</span> 
                     
                        Asthme  <?php echo $this->formRow($form->get('asthmeAM'));?>
                     </label>
								</div>
							</td>

						</tr>

						<tr id="labelDesAntecedentsMedicaux_1" style="width: 100%;">
							<!-- Emplacement des autres antecedents mï¿½dicaux ajouter ï¿½ partir du champ autre -->
						</tr>


						<tr style="width: 100%;">
							<td id="BUcheckbox" colspan="3" style="width: 60%;">
								<div id="imageIconeAjouterLabel">
                      <?php echo $this->formRow($form->get('nbCheckboxAM'));?>
                      <label
										style="width: 58%; height: 30px; text-align:right;">
                        Autres  <?php echo $this->formRow($form->get('autresAM'));?>
                        <img id="imgIconeAjouterLabel"
										style='cursor: pointer; padding-right: 5px; padding-left: 10px; padding-bottom: 6px;'
										src='<?php echo $this->basepath().'/images_icons/Add14X14.png'?>' />
									</label>
								</div>
							</td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>

						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 20%; padding-bottom: 5px; padding-top: 35px;'><div
									style="float: left;" id="TerminerAntecedentMedicaux">Terminer</div></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						
						
						</tr>
					
					</table>


					<script> 
              var myArrayAntMed = [''];
              var i = 1;
           </script>
           
           <script> 
        	  autocompletionAntecedent(myArrayAntMed);
           </script>



					<script> 
              var myArrayAntMedPat = [''];
              var i = 1;
           </script>
           
           <script> 
           $('#nbCheckboxAM').val('<?php echo $this->nbAntMedPat;?>');
           setTimeout(function(){
        	   affichageAntecedentsMedicauxDuPatient('<?php echo $this->nbAntMedPat;?>' , myArrayAntMedPat);
           }, 500);
           </script>


					<table id="AntecedentChirurgicaux" style="width: 100%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									LES ANT&Eacute;C&Eacute;DENTS CHIRURGICAUX
								</div>
							</td>
						</tr>
						
						<tr class="observation"><td><?php echo $this->formRow($form->get('text_chirur'));?> </td></tr>
							
						<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 100%; padding-bottom: 5px;'><div
									style="float: left;" id="TerminerAntecedentChirurgicaux">Terminer</div></td>
						
						
						<tr>
					
					</table>

				

					<script>
             var temoinAlcoolique = <?php echo $this->donneesAntecedentsPersonnels['AlcooliqueHV'];?>;
             var temoinFumeurHV   = <?php echo $this->donneesAntecedentsPersonnels['FumeurHV'];?>; var nbPaquetFumeurHV = <?php echo (float)$this->donneesAntecedentsPersonnels['nbPaquetFumeurHV'];?>;
             var temoinDroguerHV  = <?php echo $this->donneesAntecedentsPersonnels['DroguerHV'];?>;
             var temoinAutreHV  = <?php echo $this->donneesAntecedentsPersonnels['AutresHV'];?>;
             var temoinDiabeteAM = <?php echo $this->donneesAntecedentsPersonnels['DiabeteAM'];?>;
             var temoindrepanocytoseAM = <?php echo $this->donneesAntecedentsPersonnels['drepanocytoseAM'];?>;
             var temoinhtaAM = <?php echo $this->donneesAntecedentsPersonnels['htaAM'];?>;
             var temoindislipidemieAM = <?php echo $this->donneesAntecedentsPersonnels['dislipidemieAM'];?>;
             var temoinasthmeAM = <?php echo $this->donneesAntecedentsPersonnels['asthmeAM'];?>;
           </script>

				</div>

				<!--****** ========================================================================= ****** -->
				<!--****** ======================= FIN TAB ANTECEDENTS PERSONNELS ================== ****** -->
				<!--****** ========================================================================= ****** -->


				

				<div id="tabss-2">
					<!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
					<!--****** ================== ANTECEDENTS FAMILIAUX ================== ****** -->
					<table id="" style="width: 50%;">
						<tr style="width: 100%;">
							<td style="">
								<div
									style="width: 100%; font-family: Times New Roman; color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;">
									<iS style='font-size: 25px;'>&curren;</iS>
									ANT&Eacute;C&Eacute;DENTS FAMILIAUX
								</div>
							</td>
						</tr>
					<tbody id="" style=" float:left;">
						<tr style="width: 50%;">
								<td id="BUcheckbox"  style="width: 50%;">
								<div style="float: left;">
									<label style="width: 130px; height: 30px; text-align: right;">Diab&egrave;te <?php echo $this->formRow($form->get('DiabeteAF'));?></label>
								</div>
								<div style="float: left" id="">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteDiabeteAF'));?></label>
								</div>
							</td>
					</tr>
					<tr style="width: 50%;">
							<td id="BUcheckbox"  style="width: 50%;">
								<div style="float: left;">
									<label style="width: 130px; height: 30px; text-align: right;">Dr&eacute;panocytose <?php echo $this->formRow($form->get('DrepanocytoseAF'));?></label>
								</div>
								<div style="float: left" id="">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteDrepanocytoseAF'));?></label>
								</div>
							</td>
							
						</tr>
						<tr style="width: 50%;">
								<td id="BUcheckbox" style="width: 50%;">
								<div style="float: left;">
									<label style="width: 130px; height: 30px; text-align: right;">HTA <?php echo $this->formRow($form->get('htaAF'));?></label>
								</div>
								<div style="float: left" id="DivNoteHtaAF">
									<label style="width: 260px; height: 30px; text-align: right;">Note <?php echo $this->formRow($form->get('NoteHtaAF'));?></label>
								</div>
							</td></tr>
							</tbody>
					<tbody id="" style="width: 0%;float:right;">
						<tr>
							<td id="BUcheckbox" style="width: 50%;">
								<div  style="float: left" id="DivNoteHtaAF">
									<label   class=" autreAntF" style="width: 410px; height: 120px; text-align: right;">Autres Ant&eacute;c&eacute;dents Familiaux <?php echo $this->formRow($form->get('NoteAutresAF'));?></label>
								</div>
							</td>
						</tr>
					</tbody>
						</table>
						
					<script>
               var temoinDiabeteAF = <?php echo $this->donneesAntecedentsFamiliaux['DiabeteAF'];?>;
               var temoinDrepanocytoseAF = <?php echo $this->donneesAntecedentsFamiliaux['DrepanocytoseAF'];?>;
               var temoinhtaAF = <?php echo $this->donneesAntecedentsFamiliaux['htaAF'];?>;
           </script>

					

				</div>

			


			
		</div>
		
			
		
 </div>

</div>
       
       
				<div id='motifsAdmissionConstanteClick' style='font-family: police2;font-size: 17px; font-weight: bold;'>Constantes</div>
		<div style='max-height: 100px;'>
 <?php echo $this->formHidden($form->get('id_patient'));?>
           <?php echo $this->formHidden($form->get('id_medecin'));?>
           <?php echo $this->formHidden($form->get('id_cons'));?>
           <?php  echo $this->formHidden($form->get('id_accouchement'));?>
            <?php echo $this->formHidden($form->get('id_admission'));?>
            
            

     <!-- **************************************************************************************************************** -->
			<!-- SOUS ACCORDEON MOTIF D'ADMISSION ET CONSTANTES -->
			<!--div id="accordionss"-->
			
				
				<!--**************** sous accordeon LES CONSTANTES ************************-->
				<!--**************** sous accordeon LES CONSTANTES ************************-->
				<!-- **2** -->
				
				<div style="max-height: 500px;">
					<table id="" style="width: 100%;">

						<tr class="constante_go">
						<td class="constante_go" style="width:30%; ">
	           
	           <div style="float: left; width: 30%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> Temp&eacute;rature </label>
		       </div>
		       <div style="float: left; width: 25%; ">
			       <label style="width: 90%; height: 30px; text-align: left;margin-left:10%;"> <?php echo $this->formRow($form->get('temperature'));?></label>
		       </div>							
		    </td>
						<td class="constante_go" style="width:20%;">
	           
	           <div style="float: left; width: 30%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> Poids</label>
		       </div>
		       <div style="float: left; width: 30%; ">
			       <label style="width: 90%; height: 30px; text-align: left;margin-left:18%;"> <?php echo $this->formRow($form->get('poids'));?></label>
		       </div>	
		        </td>
							<td class="constante_go" style="width: 30%; ">
	           
	           <div style="float: left; width: 28%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"title="Pression arterielle"> PA(mmHg) </label>
		       </div>
		       <div style="float: left; width: 23%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('tensionmaximale'));?>/</label>      	       
		       </div>
		        <div style="float: left; width: 23%; ">
		<label style="width: 90%; height: 30px; text-align: left;"><?php echo $this->formRow($form->get('tensionminimale'));?></label>
		       </div>									
		    </td>
				
				<td class="constante_go" style="width:30%;">
	           
	           <div style="float: left; width: 30%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> Pouls </label>
		       </div>
		       <div style="float: left; width: 30%; ">
			       <label style="width: 90%; height: 30px; text-align: left;margin-left:18%;"> <?php echo $this->formRow($form->get('pouls'));?></label>
		       </div>	
		        </td>	
		    </tr>
		    	<tr class="constante_go">
		  			
					
		        	
								</tr>
				
				
				</table>
			 </div>
				 </div>
				 <div id="" style='font-family: police2;font-size: 17px; font-weight: bold;'>Interrogatoire </div>
 <div style="max-height: 300px;">
 
 
     
           <div id="divEtatcivil" style='max-height: 300px;'>
		 
		   <table id="" style="width: 100%;">
		   		   
		     <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 25%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Ethnie </label>
		       </div>
		       <div style="float: left; width: 40%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('ethnie'));?></label>
		       </div>
			  		
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Religion </label>
		       </div>
		       <div style="float: left; width: 40%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('religion'));?></label>
		       </div>
			   
								
		    </td>
		        <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Niveau </label>
		       </div>
		       <div style="float: left; width: 80%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('niveau'));?></label>
		       </div>
			   
								
		    </td>
		  </tr>
		  
		  <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 25%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Situation Mat </label>
		       </div>
		       <div style="float: left; width: 40%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('situation'));?></label>
		       </div>
			  		
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 25%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Profession </label>
		       </div>
		       <div style="float: left; width: 35%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('profession'));?></label>
		       </div>
			   
								
		    </td>
		        <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 25%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Source dinfo </label>
		       </div>
		       <div style="float: left; width: 65%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('source'));?></label>
		       </div>
			   
								
		    </td>
		   
		  </tr>
		  		  <tr style="width: 100%;">
		  
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Preferee </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('prefere'));?></label>
		       </div>
			   
								
		    </td>
		      </tr>
		      
		  
		   </table>
		   
		   </div>
		</div>
						
      <div style='font-family: police2;font-size: 17px; font-weight: bold;'>Examen Physique</div>
           
           <div id="divEtatcivil" style='max-height: 400px;'>
		 
		   <table id="" style="width: 100%;">
		   
		   
		     <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Varices </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('varices'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note <?php echo $this->formRow($form->get('notevarice'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Exophtalmie </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('exophtalmi'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('noteexoph'));?> </label>
			   </div>
								
		    </td>
		  </tr>
		  <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Alergie </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('alergiecuv'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('note_cuve'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Vulve </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('vulve'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('notevu'));?> </label>
			   </div>
								
		    </td>
	 	  </tr> 
	 	   <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Perinees </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('perine'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('noteperine'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Col </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('col'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_col'));?> </label>
			   </div>
								
		    </td>
	 	  </tr>      
		
		 <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Uterus </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('uterus'));?></label>
		       </div>
		        <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_uterus'));?> </label>
			   </div>
		         </td>
	 	  </tr>
	 	   <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Annexes</label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('annexe'));?></label>
		       </div>
		        <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_annexe'));?> </label>
			   </div>
		       	       
		         </td>
		          <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Pertes</label>
		       </div>
		       <div style="float: left; width: 21%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('pertes'));?></label>
		       </div>
		        <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('note_pertes'));?> </label>
			   </div>
		       	       
		         </td>
	 	  </tr>
		
		</table>
	
	
		</div>
			  <div style='font-family: police2;font-size: 17px; font-weight: bold;'>Examens Complementaires</div>
           
           <div id="divEtatcivil" style='max-height: 200px;'>
		 
		   <table id="" style="width: 100%;">
		   						<tr class="observation"><td><?php echo $this->formRow($form->get('text_chirur'));?> </td></tr>
		   
		    	<tr style="width: 100%;">
							<td class='block' id='thoughtbot'
								style='display: inline-block; vertical-align: bottom; width: 10%; padding-bottom: 5px;'><div
									style="float: left;" id="TerminerAntecedentChirurgicaux">Terminer</div></td>
						
						
						</tr>
		
           </table>

		  </div>
		  <div style='font-family: police2;font-size: 17px; font-weight: bold;'>Contraception</div>
		  		   
		   <div id="divEtatcivil" style='max-height: 200px;'>
		    
		 
		   <table id="" style="width: 100%;">
		   
		   
		     <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 18%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">M&eacute;thode Appoprie&eacute; Choisie </label>
		       </div>
		       <div style="float: left; width: 10%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('pilule'));?></label>
		       </div>
		       </td>
		       </tr>	
		
		</table>
         </div>
         
		            <div style='font-family: police2;font-size: 17px; font-weight: bold;'> Visites </div>
            <div>
                        <div style="margin-bottom: 5px; border-bottom: 1.5px solid #cccccc; margin-top:-15px;"></div>

                        

                        <div id="" style="width: 100%; height:350px;" >
<?php echo $this->headScript()->appendFile($this->basePath().'/js/maternite/planification/visite.js');
?>
                            <table class="table table-bordered" style="width: 100%; margin-bottom: 0px; margin-left: 0px; ">
                                <thead style="width: 100%;">
                                <tr style="width: 100%; height: 40px; font-family: police2;">
                                
                                   <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">Date</th>
                                    
                                    <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">DateDernierRegle</th>
                                    <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">Poids</th>
                                    <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">TA</th>
                                     <th style="width: 28%; font-weight: bold; font-size: 15px; text-align: left;">Observation</th>
                                     <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">Unites</th>
                                     <th style="width: 10%; font-weight: bold; font-size: 15px; text-align: left;">DateProchainRV</th>
                                     
                                    
                                    
                                    <th style="width: 9%;  font-weight: bold; font-size: 15px; ">Options</th>
                                </tr>
                                </thead>
                            </table>

                            <div id="Visite_0">
                                <!-- A ne pas enlever -->
                            </div>

                            <!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
                            <!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
                            <div id="controls_complication" style="margin-top: 20px; width: 100%;">
                                <div style="width: 100%;">
                                    <div style="width: 3%; float: left; cursor: pointer; " id="supprimer_comp">
                                        <img style='margin-left: 5px;' src='../images_icons/moin-green.png' title='supprimer' />
                                    </div>
                                    <div style="width: 3%; float: left; cursor: pointer; " id="ajouter_comp">
                                        <img style='margin-left: 5px;' src='../images_icons/plus-green.png' title='ajouter' />
                                    </div>
                                </div>
                            </div>

                         
                         
                    <!--********************* BOUTON VALIDER OU MODIFIER ************************-->
                    <!--********************* BOUTON VALIDER OU MODIFIER ************************-->
                  
     <table style="width: 90%; float:right; position: relative; right: 0;">
                        <tr style="width: 100%;">
                            <th style="height:15px;">
                                <div id='bouton_Medicament_modifier_demande' style="float:right;">
                                    <button >Modifier</button>
                                </div>
                                <div id='bouton_Medicament_valider_demande' style="float:right;">
                                    <button >Valider</button>
                                </div>
                            </th>
                        </tr>
                    </table>

                        </div>


                        <!--********************* CHARGEMENT DES DONNEES  ************************-->
                        <!--********************* CHARGEMENT DES DONNEES  ************************-->
                        <!--********************* CHARGEMENT DES DONNEES  ************************-->
                     <?php
                            $nbcauseco = count($this->listeComplicationObstetricales);
                            if ($nbcauseco == 0) {
                                $nbcauseco = 1;
                            }
                            $tableauDesCauses = array();
                            ?>
                           <script>
                          
                          // ValiderComplication();
                                var myArrayComp = [''];
                                var icmpt = 1;
                            </script>
                            

                            <script>
                            partDefautComplication(myArrayComp,'<?php echo $nbcauseco; ?>');
                                var indligne = 0;
                                //alert(myArrayComp);
                            </script>
            
                             
                        </div>
		
		
	<div style='font-family: police2;font-size: 17px; font-weight: bold;'>Autres raisons de la visite</div>
	
		<div id="divEtatcivil" style='max-height: 350px;'>
		  <table id="" style="width: 100%;">
		   
		   
		     <tr style="width: 100%;">
		    <td class="antecedent_go" style="width: 50%; ">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Arret </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('varices'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note <?php echo $this->formRow($form->get('notevarice'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Change </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('exophtalmi'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note&nbsp;&nbsp; <?php echo $this->formRow($form->get('noteexoph'));?> </label>
			   </div>
								
		    </td>
		  </tr>
		  <tr style="width: 100%; ">
		    <td class="antecedent_go" style="width: 50%;">
	           
	           <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Bilan </label>
		       </div>
		       <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('alergiecuv'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 90%; height: 30px; text-align: left;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('note_cuve'));?> </label>
			   </div>
								
		    </td>
		    
		    <td class="antecedent_go" style="width: 50%; ">
	           <div style="float: left; width: 20%; ">
			       <label style="width: 90%; height: 30px; text-align: left;">Info </label>
		       </div>
		       <div style="float: left; width: 15%; ">
			       <label style="width: 90%; height: 30px; text-align: left;"> <?php echo $this->formRow($form->get('vulve'));?></label>
		       </div>
			   <div style="float: right; width: 60%; " id="rh">
				   <label class="" style="width: 95%; height: 30px; text-align: right;">Note &nbsp;&nbsp;<?php echo $this->formRow($form->get('notevu'));?> </label>
			   </div>
								
		    </td>
	 	  </tr> 
	 	  </table>
		</div>	
		
			<div style='font-family: police2;font-size: 17px; font-weight: bold;'>Observations</div>
	
		
		<div id="divEtatcivil" style='max-height: 350px;'>
	
		<div class="rendezvous">
                    <hass><input type="submit"  title="Imprimer" name="observation_go" id="observation_go"> </hass>
                </div> 
                  <div style=" padding-bottom:40px; margin-bottom: 10px; border-bottom: 1px dashed black; margin-left: 0px; margin-right: 0px;"></div>
		  
	<table style="width: 100%;"> 
		 	
		<tr class="observation"><td><?php echo $this->formRow($form->get('text_observation'));?> </td></tr>
		
	</table>
		</div>
		<div style='font-family: police2;font-size: 17px; font-weight: bold;'>Effets secondaires</div>
	
		
		<div id="divEtatcivil" style='max-height: 350px;'>
	
		<div class="rendezvous">
                    <hass><input type="submit"  title="Imprimer" name="observation_go" id="observation_go"> </hass>
                </div> 
                  <div style=" padding-bottom:40px; margin-bottom: 10px; border-bottom: 1px dashed black; margin-left: 0px; margin-right: 0px;"></div>
		  
	<table style="width: 100%;"> 
		 	
		<tr class="observation"><td><?php echo $this->formRow($form->get('text_observation'));?> </td></tr>
		
	</table>
		</div>
		
		</div>
		
		
		<table style="width: 100%; margin-top: 20px;">
		<tr>
			<td style="background-color: #eeeeee; height: 40px; width: 100%;">
				<p style="text-align: center;">
					<button id="annuler2"
						style="font-family: police2; font-size: 18px; font-weight: bold;">
						Annuler</button>
					<button name="terminer2" id="terminer3" 
						style="font-family: police2; font-size: 18px; font-weight: bold;">
						Terminer</button>
				</p>
			</td>
		</tr>
	</table>

	<!-- POP UP pour Confirmation Annulation -->
	<div id="confirmation2" title="Confirmation de l'annulation"
		style="display: none;">
		<p style="font-size: 16px;">
			<span style="float: left; margin: 0 0px 20px 0;"> <img
				src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

				Etes-vous s&ucirc;r de vouloir annuler les modifications ?
			</span>
		</p>
	</div>
		<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU C'EST LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

//if($role == 'infirmier'){ ?>
<script>
$(".hosprend").toggle(false);

</script>

<?php echo $this->form()->closeTag();?>
</div>
<script>
jsPagination();
getMotif($('#motif_ad').val());
getCycle($('#regularite').val());
getContraception($('#contraception').val());
getAccouchement($('#type_accouchement').val());
getQuantite($('#quantite_regle').val());
getTest($('#test_emmel').val());
getExamenMaterniteDonnee5($('#examen_maternite_donnee5').val());

getExamenMaterniteDonnee3($('#examen_maternite_donnee3').val());
$('#motif_ad').attr('disabled', true);

</script>	

			 

<?php echo $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.cons.js');?>